name: 🔒 Container Security Pipeline
on:
  push:
    branches: [ "trivy-test" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: gitsecops-app
  IMAGE_TAG: ${{ github.sha }}
  TRIVY_DOCKER_IMAGE: $IMAGE_NAME:$IMAGE_TAG

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    # FASE 1: PREPARACIÓN
    - name: 🛠 Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # FASE : CACHE
    - name: Cache Trivy DB
      uses: actions/cache@v3
      with:
        path: ~/.cache/trivy
        key: ${{ runner.os }}-trivy-db

    - name: Run Trivy config scanner
      uses: aquasecurity/trivy-action@0.32.0
      with:
        scan-type: 'config'
        hide-progress: true
        output: config.txt
        #format: 'sarif'
        #output: 'trivy-results.sarif'
        #exit-code: '1'
        severity: 'CRITICAL,HIGH'

    # FASE 2: SAST (ANÁLISIS ESTÁTICO)
    - name: "🔍 [SAST] Secrets Scanning (Code)"
      uses: aquasecurity/trivy-action@0.32.0
      with:
        scan-type: 'fs'
        scanners: 'secret'
        format: 'table'
    
    # FASE 3: BUILD
    - name: "🏗 Build Docker Image"
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
    
    # FASE 4: SCA (DEPENDENCIAS)
    - name: "📦 [SCA] Vulnerability Scan (OS/Libraries)"
      uses: aquasecurity/trivy-action@0.32.0
      with:
        image-ref: '${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG}}'
        severity: 'CRITICAL,HIGH,MEDIUM'
        vuln-type: 'os,library'
        format: 'sarif'
        output: 'trivy-vulns.sarif'

    # FASE x: SCA (test)
    - name: "📦 [SCA] Vulnerability Scan (OS)"
      uses: aquasecurity/trivy-action@0.32.0
      with:
        image-ref: '${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG}}'
        severity: 'CRITICAL,HIGH,MEDIUM'
        vuln-type: 'os'
        output: trivy.txt

    - name: Publish Trivy Output to Summary
      id: trivy_head
      run: |
        if [[ -s trivy.txt ]]; then
          {
            echo "### 🛡️ Trivy Config/Scan Results"
            echo "<details><summary>Ver detalles</summary>"
            echo ""
            echo '```'
            echo 'Summary Configs (IaC/Dockerfile)'
            cat config.txt
            echo 'Summary OS (Image Container)'
            cat trivy.txt | head -n 1000  # Limita la longitud
            echo '```'
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY
        else
          echo "Sin resultados en el escaneo Trivy (trivy.txt vacío)." >> $GITHUB_STEP_SUMMARY
        fi

    - name: 📊 Extraer resumen para Slack
      id: trivy_summary
      run: |
        # Extraer secciones con severidades
        resumen=$(awk '/Total:/ && ($0 ~ /HIGH: [1-9]|CRITICAL: [1-9]/) { print; exit }' trivy.txt)
        
        echo "slack_summary=$resumen" >> $GITHUB_OUTPUT
        
    - name: Send Trivy Report to Slack
      if: always()
      uses: slackapi/slack-github-action@v2.1.1
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload: >
          {
            "text": ":lock: *Análisis Trivy finalizado* (`${{ job.status }}`)",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*🔐 Trivy Scan*\n*📦 Repositorio:* `${{ github.repository }}`\n*🌿 Rama:* `${{ github.ref_name || github.ref }}`\n*⚠️ Vulnerabilidades encontradas:* `${{ steps.trivy_summary.outputs.slack_summary }}`"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*👉 [Ver resumen del escaneo en GitHub]*\n(${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
                }
              }
            ]
          }

    # FASE 5: REPORTING
    - name: "📊 Upload SAST/SCA Results"
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-vulns.sarif'
        category: my-analysis-tool